apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rogfk-no

resources:
  - ../../../base

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-file-service_rogfk-no"
      - op: replace
        path: "/metadata/labels/fintlabs.no~1org-id"
        value: "rogfk.no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "rogfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "rogfk.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "rogfk-no"
    target:
      kind: Application
      name: fint-flyt-file-service

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-file-service-azure-blob-storage_rogfk_no"
      - op: replace
        path: "/metadata/labels/fintlabs.no~1org-id"
        value: "rogfk.no"
    target:
      kind: AzureBlobContainer
      name: fint-flyt-file-service-azure-blob-storage
