fint:
  org-id: novari.no

novari:
  flyt:
    file-service:
      time-to-keep-files-in-days: 180
      local-security:
        permit-all-enabled: true

    web-resource-server:
      security:
        api:
          internal:
            enabled: false
          internal-client:
            enabled: false
          external:
            enabled: false

  kafka:
    default-replicas: 1
    topic:
      org-id: novari-no

spring:
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8091
