apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fint-flyt-file-service
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`hostname`) && PathPrefix(`path`)
      kind: Rule
      services:
        - name: fint-flyt-file-service
          port: 8080